---
- name: Ensure dependencies are installed.
  apt:
    name:
      - curl
      - apt-transport-https
      - gnupg
    state: present

- name: Get the Jenkins apt repository key.
  ansible.builtin.get_url:
    url: "{{ jenkins_repo_key_url }}"
    dest: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'
    force: true

- name: Ensure /etc/apt/keyrings/jenkins-keyring.asc is world-readable
  ansible.builtin.file:
    path: /etc/apt/keyrings/jenkins-keyring.asc
    mode: '0644'
    owner: root
    group: root
  become: true

# - name: Add Jenkins repository using deb822_repository
#   ansible.builtin.deb822_repository:
#     name: jenkins
#     types: [deb]
#     uris: "{{ jenkins_repo_url }}"
#     suites: [trixie]
#     components: [stable]
#     signed_by: /etc/apt/trusted.gpg.d/jenkins.asc
#     state: present
#   when: jenkins_repo_url is defined and jenkins_repo_url != ""
    
- name: Add Jenkins APT repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] {{ jenkins_repo_url }}"
    filename: jenkins
    state: present
  when: jenkins_repo_url is defined and jenkins_repo_url != ""    

- name: Update apt package cache - before getting Jenkins packages
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Download specific Jenkins version.
  get_url:
    url: "{{ jenkins_pkg_url }}/jenkins_{{ jenkins_version }}_all.deb"
    dest: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  when: jenkins_version is defined

- name: Check if we downloaded a specific version of Jenkins.
  stat:
    path: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
  register: specific_version
  when: jenkins_version is defined

- name: Install our specific version of Jenkins.
  apt:
    deb: "/tmp/jenkins_{{ jenkins_version }}_all.deb"
    state: present
  when: jenkins_version is defined and specific_version.stat.exists
  notify: configure default users

- name: Ensure Jenkins is installed.
  apt:
    name: jenkins
    state: "{{ jenkins_package_state }}"
  notify: configure default users
